management:
  server:
    port: ${bb_health:8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/print-service/1.0.0

amazon:
  bb-printer-bucket: uk-gov-dft-${bb_env}-printer
  bb-badge-bucket: uk-gov-dft-${bb_env}-badge

