blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
  referencedataservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /

management:
  server:
    port: ${bb_health:8081}

server:
  port: ${bb_port:8080}

amazon:
  bb-printer-bucket: uk-gov-dft-${bb_env}-printer
  bb-badge-bucket: uk-gov-dft-${bb_env}-badge

