blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  reference-data-service:
    service-host:
      host: referencedata-service

amazon:
  bb-printer-bucket: uk-gov-dft-${bb_env:ci}-printer
  bb-badge-bucket: uk-gov-dft-${bb_env:ci}-badge

ftp:
  host: ${SFTP_HOST:sftp-server}
  port: ${SFTP_PORT:22}
  user: foo
   ***REMOVED***
  dropbox: /upload
  knownhosts: ~/.ssh/sftp_known_hosts
